import { fetchAllTopics, fetchDrucksacheSummary, fetchSummaries } from "@/lib/api";
import type { Top } from "@/lib/api";
import { resolveHaushaltswoche } from "@/lib/haushaltswoche";
import HaushaltswochePage from "./HaushaltswochePage";
import BackButton from "@/components/BackButton";
import ParliamentChart from "@/components/ParliamentChart";
import ThemeToggle from "@/components/ThemeToggle";
import GeneralSummary from "@/components/GeneralSummary";
import VoteSummaryCard from "@/components/VoteSummaryCard";
import DrucksacheList, { type DrucksacheListItem } from "@/components/DrucksacheList";

const normTitle = (s: string) =>
  s.replace(/[–—-]/g, "-").replace(/\s+/g, " ").trim().toLowerCase();

/** One entry per Drucksache tied to the TOP (top-level + subtopics), each with its
 *  (cache-warm, generated by /summaries just before) Drucksachen-Zusammenfassung. */
async function fetchTopDrucksachen(top: Top | undefined): Promise<DrucksacheListItem[]> {
  if (!top) return [];
  const rows: { nummer: string; pdfUrl: string; subtopicTitle?: string }[] = [];
  if (top.drucksache) {
    rows.push({ nummer: top.drucksache, pdfUrl: top.drucksache_url });
  }
  for (const s of top.subtopics ?? []) {
    if (s.drucksache) {
      rows.push({ nummer: s.drucksache, pdfUrl: s.drucksache_url, subtopicTitle: s.title });
    }
  }
  return Promise.all(
    rows.map(async (r) => ({ ...r, summary: await fetchDrucksacheSummary(r.nummer) })),
  );
}

export default async function SummaryPage({
  params,
}: {
  params: Promise<{ topKey: string }>;
}) {
  const { topKey } = await params;
  const decoded = decodeURIComponent(topKey);

  const topics = await fetchAllTopics();

  // The Haushaltswoche hub itself and its Einbringung TOP (a real top_key) each get a
  // content-only view — see expandHaushaltswoche(). Neither needs the generic /summaries
  // fetch below. The Einzelplan ressort debates are NOT part of this: they're ordinary
  // TOPs and fall through to the ordinary rendering further down.
  const resolved = resolveHaushaltswoche(topics, decoded);
  if (resolved) {
    return (
      <div className="min-h-screen bg-white dark:bg-zinc-950">
        <div className="max-w-5xl mx-auto px-4 py-6">
          <div className="sticky top-0 z-20 -mx-4 px-4 py-2 bg-white/50 dark:bg-zinc-950/50 backdrop-blur flex items-center justify-between mb-4">
            <BackButton />
            <ThemeToggle />
          </div>
          <HaushaltswochePage hub={resolved.hub} view={resolved.view} allTopics={topics} />
        </div>
      </div>
    );
  }

  const summariesResult = await fetchSummaries(decoded).catch((e) => {
    console.error(`fetchSummaries failed for topKey=${decoded}:`, e);
    return null;
  });
  const summariesFailed = summariesResult === null;
  const summaries = summariesResult ?? {};

  const top = topics.find((t) => t.top_key === decoded);
  const navLabel =
    top?.top_id
      .replace("Tagesordnungspunkt ", "TOP ")
      .replace("Zusatzpunkt ", "ZP ")
      .replace("Einzelplan ", "EP ") ?? // erklärt im FAQ ("Was ist ein Einzelplan (EP)?")
    decoded;

  const general = summaries.general as { summary: string } | undefined;
  const abstimmung = summaries.abstimmung;
  // A TOP can technically have more than one recorded vote (one per subtopic), but that
  // hasn't occurred in practice yet — show the first one rather than build UI for a case
  // that doesn't exist in the data.
  const vote = abstimmung ? Object.values(abstimmung)[0] : undefined;
  const partySummaries = Object.fromEntries(
    Object.entries(summaries)
      .filter(([k]) => k !== "general")
      .map(([k, v]) => [k, v as { summary: string; refresh_count?: number }]),
  );

  // /summaries has just generated any missing Drucksachen-Zusammenfassungen for the
  // general summary, so these are cache hits.
  const drucksachen = await fetchTopDrucksachen(top);
  // The subtitle (top.title) is often literally the Drucksachentitel — it's already in
  // the list below, so drop the redundant header line in that case.
  const drucksacheTitles = drucksachen
    .map((d) => d.summary?.titel)
    .filter(Boolean)
    .map((t) => normTitle(t as string));
  const titleIsDrucksache =
    !!top?.title && drucksacheTitles.includes(normTitle(top.title));
  // Einzelplan ressort debates carry their ministry ("Geschäftsbereich des
  // Bundesministeriums für X") only in subtitle — nowhere else on the page shows it.
  const einzelplanSubtitle = top?.top_id.startsWith("Einzelplan") ? top.subtitle : "";

  const showLeftCol = Boolean(vote || general?.summary);

  return (
    <div className="min-h-screen bg-white dark:bg-zinc-950">
      <div className="max-w-5xl mx-auto px-4 py-6">
        <div className="sticky top-0 z-20 -mx-4 px-4 py-2 bg-white/50 dark:bg-zinc-950/50 backdrop-blur flex items-center justify-between mb-4">
          <BackButton />
          <ThemeToggle />
        </div>

        <div className="mb-6">
          <p className="text-xs text-zinc-400 mb-1">
            {top?.date} · {navLabel}
          </p>
          <h1 className="text-xl font-bold text-[#023047] dark:text-white flex flex-wrap items-baseline gap-x-2">
            <span>{top?.topic || top?.title || decoded}</span>
            {vote && (
              <span className="relative group shrink-0 text-base font-normal align-middle">
                <span aria-hidden="true">🗳️</span>
                <span className="sr-only">Namentliche Abstimmung</span>
                <span
                  aria-hidden="true"
                  className="absolute bottom-full left-1/2 -translate-x-1/2 mb-1.5 whitespace-nowrap rounded-lg bg-zinc-800 text-white text-xs px-2 py-1 opacity-0 group-hover:opacity-100 pointer-events-none transition-opacity duration-75 z-10 shadow-lg"
                >
                  Namentliche Abstimmung
                </span>
              </span>
            )}
          </h1>
          {top?.title && top.title !== top?.topic && !titleIsDrucksache && (
            <p className="text-sm text-zinc-600 dark:text-zinc-300 mt-1">{top.title}</p>
          )}
          {einzelplanSubtitle && (
            <p className="text-sm text-zinc-600 dark:text-zinc-300 mt-1">{einzelplanSubtitle}</p>
          )}

          {drucksachen.length > 0 ? (
            <DrucksacheList items={drucksachen} />
          ) : (
            top?.subtopics &&
            top.subtopics.length > 0 && (
              <ul className="mt-2 space-y-0.5">
                {top.subtopics.map((s) => (
                  <li key={s.key} className="text-sm text-zinc-600 dark:text-zinc-300">
                    <span className="font-medium text-zinc-700 dark:text-zinc-200">
                      {s.key})
                    </span>{" "}
                    {s.title}
                  </li>
                ))}
              </ul>
            )
          )}
        </div>

        {summariesFailed ? (
          // The backend fetch failed (e.g. mid cold-start) rather than genuinely
          // returning nothing — showing the chart here would render every party
          // as "Keine Zusammenfassung verfügbar.", indistinguishable from that
          // legitimate empty state. A reload almost always fixes it once the
          // backend is warm.
          <div className="max-w-xl border border-zinc-200 dark:border-zinc-700 rounded-xl px-4 py-3 text-sm text-zinc-500 dark:text-zinc-400">
            Die Zusammenfassungen konnten gerade nicht geladen werden. Bitte Seite erneut
            laden.
          </div>
        ) : (
          /* Two-column layout: general summary left, chart + party card right */
          <div className="flex flex-col gap-6 md:flex-row md:gap-8">
            {showLeftCol && (
              <div className="md:w-2/5 shrink-0 flex flex-col gap-4">
                {general?.summary && (
                  <GeneralSummary initialSummary={general.summary} topKey={decoded} />
                )}
                {vote && <VoteSummaryCard vote={vote} />}
              </div>
            )}

            <div className="flex-1 min-w-0">
              <ParliamentChart
                summaries={partySummaries}
                topKey={decoded}
                abstimmung={abstimmung}
              />
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
