[theme]
primaryColor="#FFB703"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#8ECAE6"
textColor="#023047"
font="sans serif"

[theme.sidebar]
backgroundColor="#023047"
textColor="#FFFFFF"
primaryColor="#FFB703"
